### ISSUE TITLE
Negetive value or higher

### ISSUE THREAD

**Issue by shaon2016** [oli107/material-range-bar#135] opened 2018-05-13 04:20 UTC
I have set tick start 0 and and tick end 5000. But sometime when scrolling left to right it passes the 5000 value and sometimes it passes the left value 0 to -1,-2 etc..

       ` <com.appyvet.materialrangebar.RangeBar xmlns:app="http://schemas.android.com/apk/res-auto"
                                 android:id="@+id/priceRangeBar"
                                 android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:layout_toLeftOf="@id/textMax1"
                                android:layout_toRightOf="@id/textMin1"
                                app:mrb_pinMaxFont="8sp"
                                app:mrb_pinTextColor="@color/white"
                                app:mrb_rangeBarPaddingBottom="12dp"
                                app:mrb_selectorBoundaryColor="@color/colorAccent"
                                app:mrb_selectorBoundarySize="1dp"
                                app:mrb_selectorColor="@color/colorAccent"
                                app:mrb_selectorSize="10dp"
                                app:mrb_tickEnd="5000"
                                app:mrb_tickInterval="1"
                                app:mrb_tickStart="0"
                                />`

How to solve this?

**Comment by swbradshaw** [comment] 2018-06-06 19:32
Dupe of #39?

**Comment by krazykira** [comment] 2018-06-18 10:03
probably fixed in version #137

**Closed by krazykira** 2018-06-18 10:03 UTC
